language: ruby
rvm:
- 2.1
install: bundle install
script: bundle exec jekyll build
after_success: bundle exec s3_website push
branches:
  only:
  - master
env:
  global:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      - secure: pYlawj0x+kMGSofhExDYjXJSi2DeZSweF7jNzdbG7E3UK1RJXfq4k6w0g+XE2WchDnN9+i/izHHRYLwD0z1UEP+r/3MRGCElOZ23IesdU+uznuOfubBEtVPPlYtyKvWE8glJUVV4AMLmGBwTPn/i4wWMEbsVFTspG/lFBeGWxNQ=
      - secure: GlwQQii7cVm/2TJKfA0tjFEz7R6PdS5v2olie4VkscrEZ8ZpY+6KqQ24xfhTnVlMLMTgn7aCaUKCmopmTwMGfDrix8Z9zTg6p6t19FznjrdlPlyqVLvqTgw9mYpGargVHvFTIrRXm9GRDKeBYxuR7QInRMcShM4pSBHKePpMZ2E=