language: ruby
rvm:
- 2.1
install: bundle install
script: bundle exec jekyll build
after_success: bundle exec s3_website push
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: alR0XjTzPe05HrXyHrMzaZoAyqKHS6/UrRuQftEVsCMsunE5AxB8LJNWWb/I4NPXnX9foe1WvsEg/qOQbeX7H2xtbK/xNdKBUvH56DZGjyqYvPkGZtUTsGZ2/urWG/eHjm/DN4+C/K29CqbekmzkQnvUwYUo5+5v+x5N8KvOHdk=
  - secure: CMvBMoLKhWBPzIEFTYSPZGhP0dEUSArop0+qFFsfWyoNW2h7pUwJBUZh8gIFPyYdWcN5yv9BTu1CwCvuFLpR8NvLgcp0/PszcS+eK96aYPyDV+az7hs1Gl+O0o4z7eOasz1nveUnS87MQu4h2xm911/rM/KCieEpVp1T5nzaBqk=